name: GitHub Stats and Snake Animation
on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Update README Stats
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git pull
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit --allow-empty -m "Force stats update"
          git push

  generate-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: babar0081
          github_token: ${{ secrets.GH_TOKEN }}
          svg_out_path: dist/github-snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}