name: GitHub Stats
on:
  schedule:
    - cron: '0 */24 * * *'  # Runs every 24 hours
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update README Stats
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # The stats will auto-update using the token